package agentcli

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"sync/atomic"
	"testing"

	"github.com/xhd2015/ai-critic/cmd/agentcli/testhooks"
)

// aliasTestEnv gives a test its own HOME plus a fake `remote-agent` on PATH so
// wrapper resolution is deterministic (never the real user's binaries).
func aliasTestEnv(t *testing.T) (home string) {
	t.Helper()
	home = t.TempDir()
	testhooks.SetHomeOverride(home)
	t.Cleanup(testhooks.ResetInProcessOverrides)

	binDir := filepath.Join(t.TempDir(), "path-bin")
	if err := os.MkdirAll(binDir, 0755); err != nil {
		t.Fatalf("MkdirAll(%s) error = %v", binDir, err)
	}
	fake := filepath.Join(binDir, "remote-agent")
	if err := os.WriteFile(fake, []byte("#!/bin/sh\nexit 0\n"), 0755); err != nil {
		t.Fatalf("write fake remote-agent error = %v", err)
	}
	t.Setenv("PATH", binDir)
	return home
}

type aliasCLIResult struct {
	stdout string
	stderr string
	err    error
}

func runAliasCLI(t *testing.T, args ...string) aliasCLIResult {
	t.Helper()
	return runAliasCLIStdin(t, "", args...)
}

// runAliasCLIStdin runs the CLI in-process with an optional stdin payload
// (used by `config set --token-stdin`).
func runAliasCLIStdin(t *testing.T, stdin string, args ...string) aliasCLIResult {
	t.Helper()
	var stdout, stderr bytes.Buffer

	oldStdin := os.Stdin
	if stdin != "" || hasArg(args, "--token-stdin") {
		r, w, err := os.Pipe()
		if err != nil {
			t.Fatalf("os.Pipe() error = %v", err)
		}
		if _, err := w.WriteString(stdin); err != nil {
			t.Fatalf("write stdin error = %v", err)
		}
		w.Close()
		os.Stdin = r
		defer func() {
			os.Stdin = oldStdin
			r.Close()
		}()
	}

	err := RunWithWriters(RemoteProfile(), args, &stdout, &stderr)
	return aliasCLIResult{stdout: stdout.String(), stderr: stderr.String(), err: err}
}

func hasArg(args []string, name string) bool {
	for _, a := range args {
		if a == name || strings.HasPrefix(a, name+"=") {
			return true
		}
	}
	return false
}

func readAliasStoreFile(t *testing.T, home string) aliasStore {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(home, ".ai-critic", "remote-agent-aliases.json"))
	if err != nil {
		t.Fatalf("read alias store error = %v", err)
	}
	var st aliasStore
	if err := json.Unmarshal(data, &st); err != nil {
		t.Fatalf("parse alias store error = %v", err)
	}
	return st
}

func readWrapper(t *testing.T, home, name string) string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(home, ".local", "bin", name))
	if err != nil {
		t.Fatalf("read wrapper %s error = %v", name, err)
	}
	return string(data)
}

func requireContains(t *testing.T, got, want, label string) {
	t.Helper()
	if !strings.Contains(got, want) {
		t.Fatalf("%s missing %q\ngot:\n%s", label, want, got)
	}
}

func requireNoFile(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Fatalf("%s should not exist (stat error = %v)", path, err)
	}
}

func TestAliasAddInstallsWrapperAndStore(t *testing.T) {
	home := aliasTestEnv(t)

	res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://x.dev/")
	if res.err != nil {
		t.Fatalf("alias add error = %v (stderr=%s)", res.err, res.stderr)
	}
	requireContains(t, res.stdout, "installed ~/.local/bin/xdev-agent (alias xdev → https://x.dev)", "stdout")
	requireContains(t, res.stderr, "warning: no token saved for https://x.dev", "stderr")
	requireContains(t, res.stderr, "xdev-agent config set --token-stdin", "stderr hint")

	wrapperPath := filepath.Join(home, ".local", "bin", "xdev-agent")
	info, err := os.Stat(wrapperPath)
	if err != nil {
		t.Fatalf("stat wrapper error = %v", err)
	}
	if info.Mode().Perm() != 0755 {
		t.Fatalf("wrapper mode = %v, want 0755", info.Mode().Perm())
	}
	wantBody := "#!/bin/sh\n" +
		"# generated by remote-agent alias install (alias: xdev); do not edit\n" +
		"exec remote-agent --alias xdev \"$@\"\n"
	if got := readWrapper(t, home, "xdev-agent"); got != wantBody {
		t.Fatalf("wrapper body = %q, want %q", got, wantBody)
	}

	st := readAliasStoreFile(t, home)
	if len(st.Aliases) != 1 {
		t.Fatalf("aliases = %+v, want 1 entry", st.Aliases)
	}
	if got := st.Aliases[0]; got.Name != "xdev" || got.Binary != "xdev-agent" || got.Server != "https://x.dev" {
		t.Fatalf("alias entry = %+v, want normalized server https://x.dev", got)
	}
}

func TestAliasAddDuplicateIsRejected(t *testing.T) {
	home := aliasTestEnv(t)
	if res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://x.dev"); res.err != nil {
		t.Fatalf("first add error = %v", res.err)
	}
	before := readWrapper(t, home, "xdev-agent")

	res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://other.dev")
	if res.err == nil {
		t.Fatal("duplicate add should fail")
	}
	requireContains(t, res.err.Error(), `alias "xdev" already exists`, "error")
	requireContains(t, res.err.Error(), "alias update xdev", "error hint")
	if after := readWrapper(t, home, "xdev-agent"); after != before {
		t.Fatal("duplicate add must not rewrite the wrapper")
	}
}

func TestAliasAddRefusesForeignWrapper(t *testing.T) {
	home := aliasTestEnv(t)
	binDir := filepath.Join(home, ".local", "bin")
	if err := os.MkdirAll(binDir, 0755); err != nil {
		t.Fatalf("MkdirAll error = %v", err)
	}
	foreign := filepath.Join(binDir, "xdev-agent")
	if err := os.WriteFile(foreign, []byte("#!/bin/sh\necho mine\n"), 0755); err != nil {
		t.Fatalf("write foreign error = %v", err)
	}

	res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://x.dev")
	if res.err == nil {
		t.Fatal("add over a foreign file should fail")
	}
	requireContains(t, res.err.Error(), "was not generated by remote-agent alias; pass --force", "error")
	if got, _ := os.ReadFile(foreign); string(got) != "#!/bin/sh\necho mine\n" {
		t.Fatalf("foreign file was modified: %q", got)
	}
	requireNoFile(t, filepath.Join(home, ".ai-critic", "remote-agent-aliases.json"))
}

func TestAliasAddForceOverwritesForeignWrapper(t *testing.T) {
	home := aliasTestEnv(t)
	binDir := filepath.Join(home, ".local", "bin")
	if err := os.MkdirAll(binDir, 0755); err != nil {
		t.Fatalf("MkdirAll error = %v", err)
	}
	if err := os.WriteFile(filepath.Join(binDir, "xdev-agent"), []byte("#!/bin/sh\necho mine\n"), 0755); err != nil {
		t.Fatalf("write foreign error = %v", err)
	}

	res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://x.dev", "--force")
	if res.err != nil {
		t.Fatalf("add --force error = %v (stderr=%s)", res.err, res.stderr)
	}
	requireContains(t, res.stderr, "warning: replaced ~/.local/bin/xdev-agent", "stderr")
	if got := readWrapper(t, home, "xdev-agent"); !strings.Contains(got, wrapperMarkerPrefix) {
		t.Fatalf("wrapper was not replaced with a generated one: %q", got)
	}
}

func TestAliasAddDryRunWritesNothing(t *testing.T) {
	home := aliasTestEnv(t)

	res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://x.dev", "--dry-run")
	if res.err != nil {
		t.Fatalf("dry-run error = %v", res.err)
	}
	requireContains(t, res.stdout, "[dry-run] would add alias xdev → https://x.dev", "stdout")
	requireContains(t, res.stdout, "[dry-run] would write ~/.local/bin/xdev-agent", "stdout")
	requireNoFile(t, filepath.Join(home, ".local", "bin", "xdev-agent"))
	requireNoFile(t, filepath.Join(home, ".ai-critic", "remote-agent-aliases.json"))
}

func TestAliasAddNoInstallRecordsOnly(t *testing.T) {
	home := aliasTestEnv(t)

	res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://x.dev", "--no-install")
	if res.err != nil {
		t.Fatalf("add --no-install error = %v", res.err)
	}
	requireContains(t, res.stdout, "added alias xdev → https://x.dev (no wrapper)", "stdout")
	requireNoFile(t, filepath.Join(home, ".local", "bin", "xdev-agent"))
	if st := readAliasStoreFile(t, home); len(st.Aliases) != 1 {
		t.Fatalf("store = %+v, want the alias recorded", st.Aliases)
	}
}

func TestAliasAddRejectsBadNamesAndBinaries(t *testing.T) {
	aliasTestEnv(t)

	cases := []struct {
		name string
		args []string
		want string
	}{
		{
			name: "invalid alias name",
			args: []string{"alias", "add", "bad name", "--server", "https://x.dev"},
			want: `invalid alias name "bad name"`,
		},
		{
			name: "shadow binary",
			args: []string{"alias", "add", "xdev", "--server", "https://x.dev", "--binary", "remote-agent"},
			want: "--binary remote-agent would shadow the remote-agent CLI itself",
		},
		{
			name: "missing server",
			args: []string{"alias", "add", "xdev"},
			want: "--server is required",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			res := runAliasCLI(t, tc.args...)
			if res.err == nil {
				t.Fatalf("expected error containing %q", tc.want)
			}
			requireContains(t, res.err.Error(), tc.want, "error")
		})
	}
}

func TestAliasListAndJSON(t *testing.T) {
	home := aliasTestEnv(t)

	res := runAliasCLI(t, "alias", "list")
	if res.err != nil {
		t.Fatalf("empty list error = %v", res.err)
	}
	requireContains(t, res.stdout, "no aliases", "stdout")
	requireContains(t, res.stdout, "remote-agent alias add xdev --server https://agent-xdev.example.com", "stdout hint")

	if res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://x.dev"); res.err != nil {
		t.Fatalf("add error = %v", res.err)
	}
	res = runAliasCLI(t, "alias", "list")
	if res.err != nil {
		t.Fatalf("list error = %v", res.err)
	}
	for _, want := range []string{"NAME", "BINARY", "INSTALLED", "SERVER", "TOKEN", "xdev", "xdev-agent", "missing"} {
		requireContains(t, res.stdout, want, "list stdout")
	}
	requireContains(t, res.stdout, "1 alias", "list stdout")

	res = runAliasCLI(t, "alias", "list", "--json")
	if res.err != nil {
		t.Fatalf("list --json error = %v", res.err)
	}
	var out struct {
		Aliases []aliasListEntryJSON `json:"aliases"`
	}
	if err := json.Unmarshal([]byte(res.stdout), &out); err != nil {
		t.Fatalf("unmarshal list json error = %v (%s)", err, res.stdout)
	}
	if len(out.Aliases) != 1 {
		t.Fatalf("aliases = %+v, want 1", out.Aliases)
	}
	got := out.Aliases[0]
	if got.Name != "xdev" || got.Binary != "xdev-agent" || got.Server != "https://x.dev" || !got.Installed || got.TokenSet {
		t.Fatalf("list json entry = %+v", got)
	}
	if !strings.Contains(res.stdout, filepath.Base(home)) && got.Installed != true {
		t.Fatal("expected installed wrapper to be reported")
	}
}

func TestAliasWhichResolvesNameBinaryAndActiveAlias(t *testing.T) {
	aliasTestEnv(t)
	if res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://x.dev"); res.err != nil {
		t.Fatalf("add error = %v", res.err)
	}

	byName := runAliasCLI(t, "alias", "which", "xdev")
	if byName.err != nil {
		t.Fatalf("which xdev error = %v", byName.err)
	}
	for _, want := range []string{
		"alias    xdev",
		"binary   ~/.local/bin/xdev-agent (installed)",
		"server   https://x.dev",
		"token    domain (missing)",
		"exec     remote-agent --alias xdev",
		"hint     set it with: xdev-agent config set --token-stdin",
	} {
		requireContains(t, byName.stdout, want, "which stdout")
	}

	byBinary := runAliasCLI(t, "alias", "which", "xdev-agent")
	if byBinary.err != nil {
		t.Fatalf("which xdev-agent error = %v", byBinary.err)
	}
	if byBinary.stdout != byName.stdout {
		t.Fatalf("which by binary = %q, want same as by name %q", byBinary.stdout, byName.stdout)
	}

	active := runAliasCLI(t, "--alias", "xdev", "alias", "which")
	if active.err != nil {
		t.Fatalf("active which error = %v", active.err)
	}
	if active.stdout != byName.stdout {
		t.Fatalf("active which = %q, want same as by name", active.stdout)
	}

	res := runAliasCLI(t, "alias", "which", "nope")
	if res.err == nil {
		t.Fatal("which nope should fail")
	}
	requireContains(t, res.err.Error(), `alias "nope" not found (available: xdev)`, "error")
}

func TestAliasWhichJSON(t *testing.T) {
	aliasTestEnv(t)
	if res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://x.dev"); res.err != nil {
		t.Fatalf("add error = %v", res.err)
	}
	res := runAliasCLI(t, "alias", "which", "xdev", "--json")
	if res.err != nil {
		t.Fatalf("which --json error = %v", res.err)
	}
	var out aliasWhichJSON
	if err := json.Unmarshal([]byte(res.stdout), &out); err != nil {
		t.Fatalf("unmarshal which json error = %v", err)
	}
	if out.Name != "xdev" || out.Server != "https://x.dev" || !out.Installed || !out.Identical || out.TokenSet {
		t.Fatalf("which json = %+v", out)
	}
	if out.Exec != "remote-agent --alias xdev" {
		t.Fatalf("which json exec = %q", out.Exec)
	}
}

func TestAliasUpdateServerKeepsWrapperStable(t *testing.T) {
	home := aliasTestEnv(t)
	if res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://x.dev"); res.err != nil {
		t.Fatalf("add error = %v", res.err)
	}
	before := readWrapper(t, home, "xdev-agent")

	res := runAliasCLI(t, "alias", "update", "xdev", "--server", "https://stage.dev")
	if res.err != nil {
		t.Fatalf("update error = %v (stderr=%s)", res.err, res.stderr)
	}
	requireContains(t, res.stdout, "updated alias xdev (server: https://x.dev → https://stage.dev)", "stdout")
	if after := readWrapper(t, home, "xdev-agent"); after != before {
		t.Fatal("server update must not rewrite the wrapper (the alias indirection keeps it stable)")
	}
	if st := readAliasStoreFile(t, home); st.Aliases[0].Server != "https://stage.dev" {
		t.Fatalf("store server = %q, want https://stage.dev", st.Aliases[0].Server)
	}
	which := runAliasCLI(t, "alias", "which", "xdev")
	requireContains(t, which.stdout, "server   https://stage.dev", "which stdout")
}

func TestAliasUpdateBinaryRenamesWrapper(t *testing.T) {
	home := aliasTestEnv(t)
	if res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://x.dev"); res.err != nil {
		t.Fatalf("add error = %v", res.err)
	}

	res := runAliasCLI(t, "alias", "update", "xdev", "--binary", "xdev2")
	if res.err != nil {
		t.Fatalf("rename error = %v (stderr=%s)", res.err, res.stderr)
	}
	requireContains(t, res.stdout, "updated alias xdev (binary: xdev-agent → xdev2)", "stdout")
	requireContains(t, res.stdout, "installed ~/.local/bin/xdev2", "stdout")
	requireContains(t, res.stdout, "removed ~/.local/bin/xdev-agent", "stdout")

	requireNoFile(t, filepath.Join(home, ".local", "bin", "xdev-agent"))
	wantBody := "#!/bin/sh\n" +
		"# generated by remote-agent alias install (alias: xdev); do not edit\n" +
		"exec remote-agent --alias xdev \"$@\"\n"
	if got := readWrapper(t, home, "xdev2"); got != wantBody {
		t.Fatalf("new wrapper body = %q, want %q", got, wantBody)
	}
	if st := readAliasStoreFile(t, home); st.Aliases[0].Binary != "xdev2" {
		t.Fatalf("store binary = %q, want xdev2", st.Aliases[0].Binary)
	}
}

func TestAliasUpdateUnchangedAndUnknown(t *testing.T) {
	aliasTestEnv(t)
	if res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://x.dev"); res.err != nil {
		t.Fatalf("add error = %v", res.err)
	}
	res := runAliasCLI(t, "alias", "update", "xdev")
	if res.err != nil {
		t.Fatalf("no-op update error = %v", res.err)
	}
	requireContains(t, res.stdout, "alias xdev unchanged", "stdout")

	res = runAliasCLI(t, "alias", "update", "nope", "--server", "https://x.dev")
	if res.err == nil {
		t.Fatal("update of unknown alias should fail")
	}
	requireContains(t, res.err.Error(), `alias "nope" not found (available: xdev)`, "error")
}

func TestAliasInstallRepairsMissingWrapper(t *testing.T) {
	home := aliasTestEnv(t)
	if res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://x.dev"); res.err != nil {
		t.Fatalf("add error = %v", res.err)
	}
	wrapperPath := filepath.Join(home, ".local", "bin", "xdev-agent")
	if err := os.Remove(wrapperPath); err != nil {
		t.Fatalf("remove wrapper error = %v", err)
	}

	res := runAliasCLI(t, "alias", "install", "--all")
	if res.err != nil {
		t.Fatalf("install error = %v (stderr=%s)", res.err, res.stderr)
	}
	requireContains(t, res.stdout, "installed ~/.local/bin/xdev-agent", "stdout")

	// Second run is idempotent: nothing to write.
	res = runAliasCLI(t, "alias", "install", "--all")
	if res.err != nil {
		t.Fatalf("second install error = %v", res.err)
	}
	if strings.Contains(res.stdout, "installed ~/.local/bin/xdev-agent") {
		t.Fatalf("idempotent install must not rewrite an identical wrapper, got stdout %q", res.stdout)
	}

	res = runAliasCLI(t, "alias", "install")
	if res.err == nil {
		t.Fatal("install without names or --all should fail")
	}
	requireContains(t, res.err.Error(), "alias install needs <name>... or --all", "error")

	res = runAliasCLI(t, "alias", "install", "--all", "xdev")
	if res.err == nil {
		t.Fatal("install with names and --all should fail")
	}
	requireContains(t, res.err.Error(), "takes either <name>... or --all", "error")
}

func TestAliasInstallDryRunKeepsFiles(t *testing.T) {
	home := aliasTestEnv(t)
	if res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://x.dev", "--no-install"); res.err != nil {
		t.Fatalf("add error = %v", res.err)
	}
	res := runAliasCLI(t, "alias", "install", "--all", "--dry-run")
	if res.err != nil {
		t.Fatalf("install --dry-run error = %v", res.err)
	}
	requireContains(t, res.stdout, "[dry-run] would write ~/.local/bin/xdev-agent", "stdout")
	requireNoFile(t, filepath.Join(home, ".local", "bin", "xdev-agent"))
}

func TestAliasDeleteRemovesRecordAndWrapper(t *testing.T) {
	home := aliasTestEnv(t)
	if res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://x.dev"); res.err != nil {
		t.Fatalf("add error = %v", res.err)
	}

	res := runAliasCLI(t, "alias", "delete", "xdev")
	if res.err != nil {
		t.Fatalf("delete error = %v", res.err)
	}
	requireContains(t, res.stdout, "removed alias xdev", "stdout")
	requireContains(t, res.stdout, "removed ~/.local/bin/xdev-agent", "stdout")
	requireNoFile(t, filepath.Join(home, ".local", "bin", "xdev-agent"))
	if st := readAliasStoreFile(t, home); len(st.Aliases) != 0 {
		t.Fatalf("store = %+v, want empty", st.Aliases)
	}

	res = runAliasCLI(t, "alias", "delete", "xdev")
	if res.err == nil {
		t.Fatal("second delete should fail")
	}
	requireContains(t, res.err.Error(), `alias "xdev" not found (available: none)`, "error")
}

func TestAliasDeleteKeepsForeignWrapper(t *testing.T) {
	home := aliasTestEnv(t)
	if res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://x.dev", "--no-install"); res.err != nil {
		t.Fatalf("add error = %v", res.err)
	}
	foreignPath := filepath.Join(home, ".local", "bin", "xdev-agent")
	if err := os.MkdirAll(filepath.Dir(foreignPath), 0755); err != nil {
		t.Fatalf("MkdirAll error = %v", err)
	}
	if err := os.WriteFile(foreignPath, []byte("#!/bin/sh\necho mine\n"), 0755); err != nil {
		t.Fatalf("write foreign error = %v", err)
	}

	res := runAliasCLI(t, "alias", "delete", "xdev")
	if res.err != nil {
		t.Fatalf("delete error = %v", res.err)
	}
	requireContains(t, res.stdout, "removed alias xdev", "stdout")
	requireContains(t, res.stderr, "warning: not removing ~/.local/bin/xdev-agent", "stderr")
	if got, _ := os.ReadFile(foreignPath); string(got) != "#!/bin/sh\necho mine\n" {
		t.Fatalf("foreign wrapper was modified: %q", got)
	}
}

func TestAliasDeleteDryRunAndKeepWrapper(t *testing.T) {
	home := aliasTestEnv(t)
	if res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://x.dev"); res.err != nil {
		t.Fatalf("add error = %v", res.err)
	}
	res := runAliasCLI(t, "alias", "delete", "xdev", "--dry-run")
	if res.err != nil {
		t.Fatalf("delete --dry-run error = %v", res.err)
	}
	requireContains(t, res.stdout, "[dry-run] would remove alias xdev", "stdout")
	requireContains(t, res.stdout, "[dry-run] would remove ~/.local/bin/xdev-agent", "stdout")
	if st := readAliasStoreFile(t, home); len(st.Aliases) != 1 {
		t.Fatal("dry-run must keep the alias record")
	}

	res = runAliasCLI(t, "alias", "delete", "xdev", "--keep-wrapper")
	if res.err != nil {
		t.Fatalf("delete --keep-wrapper error = %v", res.err)
	}
	if got := readWrapper(t, home, "xdev-agent"); !strings.Contains(got, wrapperMarkerPrefix) {
		t.Fatalf("--keep-wrapper must keep the file, got %q", got)
	}
}

func TestAliasUnknownSubcommand(t *testing.T) {
	aliasTestEnv(t)
	res := runAliasCLI(t, "alias", "nope")
	if res.err == nil {
		t.Fatal("unknown alias subcommand should fail")
	}
	requireContains(t, res.err.Error(), `unknown alias subcommand "nope"`, "error")
}

func TestAliasIsRemoteAgentOnly(t *testing.T) {
	aliasTestEnv(t)
	var stdout, stderr bytes.Buffer
	err := RunWithWriters(LocalProfile(), []string{"alias", "list"}, &stdout, &stderr)
	if err == nil {
		t.Fatal("local-agent alias must be unknown")
	}
	requireContains(t, err.Error(), "unknown command: alias", "error")

	// --alias is not a local-agent flag either.
	err = RunWithWriters(LocalProfile(), []string{"--alias", "xdev", "ping"}, &stdout, &stderr)
	if err == nil {
		t.Fatal("local-agent --alias must be rejected")
	}
	requireContains(t, err.Error(), "unrecognized flag: --alias", "error")
}

// aliasPingServer counts requests and answers /ping, so tests can prove which
// server a command targeted.
type aliasPingServer struct {
	*httptest.Server
	hits atomic.Int64
}

func newAliasPingServer(t *testing.T, name string) *aliasPingServer {
	t.Helper()
	s := &aliasPingServer{}
	s.Server = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		s.hits.Add(1)
		if r.URL.Path != "/ping" {
			http.NotFound(w, r)
			return
		}
		w.Write([]byte("pong"))
	}))
	t.Cleanup(s.Close)
	return s
}

func TestAliasFlagTargetsAliasServer(t *testing.T) {
	aliasTestEnv(t)
	def := newAliasPingServer(t, "default")
	aliased := newAliasPingServer(t, "xdev")

	if res := runAliasCLIStdin(t, "def-token\n", "config", "set", "--server", def.URL, "--token-stdin", "--default"); res.err != nil {
		t.Fatalf("config set default error = %v (stderr=%s)", res.err, res.stderr)
	}
	if res := runAliasCLIStdin(t, "xdev-token\n", "config", "set", "--server", aliased.URL, "--token-stdin"); res.err != nil {
		t.Fatalf("config set alias server error = %v", res.err)
	}
	if res := runAliasCLI(t, "alias", "add", "xdev", "--server", aliased.URL); res.err != nil {
		t.Fatalf("alias add error = %v (stderr=%s)", res.err, res.stderr)
	}

	res := runAliasCLI(t, "ping")
	if res.err != nil {
		t.Fatalf("plain ping error = %v", res.err)
	}
	if def.hits.Load() != 1 || aliased.hits.Load() != 0 {
		t.Fatalf("plain ping hits: default=%d aliased=%d, want 1/0", def.hits.Load(), aliased.hits.Load())
	}

	res = runAliasCLI(t, "--alias", "xdev", "ping")
	if res.err != nil {
		t.Fatalf("alias ping error = %v", res.err)
	}
	if def.hits.Load() != 1 || aliased.hits.Load() != 1 {
		t.Fatalf("alias ping hits: default=%d aliased=%d, want 1/1", def.hits.Load(), aliased.hits.Load())
	}
	requireContains(t, res.stdout, aliased.URL, "alias ping stdout")

	res = runAliasCLI(t, "--alias", "nope", "ping")
	if res.err == nil {
		t.Fatal("unknown alias should fail")
	}
	requireContains(t, res.err.Error(), `unknown alias "nope" (available: xdev)`, "error")
}

func TestAliasFlagConflicts(t *testing.T) {
	aliasTestEnv(t)
	cases := []struct {
		name string
		args []string
		want string
	}{
		{"server", []string{"--alias", "xdev", "--server", "https://x.dev", "ping"}, "--alias and --server cannot be used together"},
		{"token", []string{"--alias", "xdev", "--token", "t", "ping"}, "--alias and --token cannot be used together"},
		// --port is a local-agent flag; local-agent has no aliases, so the
		// combination cannot arise (it is rejected as an unknown flag).
		{"port", []string{"--alias", "xdev", "--port", "1234", "ping"}, "unrecognized flag: --port"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			res := runAliasCLI(t, tc.args...)
			if res.err == nil {
				t.Fatalf("expected conflict error %q", tc.want)
			}
			requireContains(t, res.err.Error(), tc.want, "error")
		})
	}
}

func TestHasGlobalFlagSkipsAliasValue(t *testing.T) {
	active = RemoteProfile()
	if !hasGlobalFlag([]string{"--alias", "xdev", "--token", "t"}, "--token") {
		t.Fatal("--token after --alias xdev must still be detected")
	}
	if hasGlobalFlag([]string{"exec", "--token", "t"}, "--token") {
		t.Fatal("command arguments must not be read as global flags")
	}
}

func TestConfigSetWritesTokenForNonDefaultServer(t *testing.T) {
	home := aliasTestEnv(t)
	if res := runAliasCLIStdin(t, "def\n", "config", "set", "--server", "https://default.dev", "--token-stdin", "--default"); res.err != nil {
		t.Fatalf("config set default error = %v", res.err)
	}
	// Unrelated config must survive a `config set`.
	cfg, err := loadConfig()
	if err != nil {
		t.Fatalf("loadConfig error = %v", err)
	}
	cfg.ProjectBindings = []projectBinding{{Server: "https://default.dev", RemoteDir: "/r", LocalPath: "/l"}}
	cfg.RememberedFlags = map[string][]string{"edit": {"--editor=cat"}}
	if err := saveConfig(cfg); err != nil {
		t.Fatalf("saveConfig error = %v", err)
	}

	res := runAliasCLIStdin(t, "other-token\n", "config", "set", "--server", "https://other.dev", "--token-stdin")
	if res.err != nil {
		t.Fatalf("config set error = %v (stderr=%s)", res.err, res.stderr)
	}
	requireContains(t, res.stdout, "domain added: https://other.dev", "stdout")
	requireContains(t, res.stdout, "token set for https://other.dev", "stdout")
	if strings.Contains(res.stdout, "other-token") {
		t.Fatal("config set must never echo the token")
	}

	cfg, err = loadConfig()
	if err != nil {
		t.Fatalf("loadConfig error = %v", err)
	}
	if cfg.Default != "https://default.dev" {
		t.Fatalf("default = %q, want unchanged https://default.dev", cfg.Default)
	}
	other := cfg.FindDomain("https://other.dev")
	if other == nil || other.Token != "other-token" {
		t.Fatalf("other domain = %+v, want token other-token", other)
	}
	if len(cfg.ProjectBindings) != 1 || cfg.RememberedFlags["edit"][0] != "--editor=cat" {
		t.Fatalf("config set dropped unrelated config: %+v", cfg)
	}
	data, err := os.ReadFile(filepath.Join(home, ".ai-critic", "remote-agent-config.json"))
	if err != nil {
		t.Fatalf("read config error = %v", err)
	}
	if !strings.Contains(string(data), "other-token") {
		t.Fatal("token was not persisted")
	}
}

func TestConfigSetTargetSpellingsAreEquivalent(t *testing.T) {
	aliasTestEnv(t)
	if res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://x.dev", "--no-install"); res.err != nil {
		t.Fatalf("alias add error = %v", res.err)
	}

	cases := [][]string{
		{"config", "set", "--server", "https://x.dev", "--token-stdin"},
		{"config", "set", "--alias", "xdev", "--token-stdin"},
		{"--alias", "xdev", "config", "set", "--token-stdin"},
		{"--server", "https://x.dev", "config", "set", "--token-stdin"},
		{"config", "set", "--server", "https://x.dev/", "--token-stdin"},
	}
	for i, args := range cases {
		res := runAliasCLIStdin(t, "tok\n", args...)
		if res.err != nil {
			t.Fatalf("case %d (%v) error = %v (stderr=%s)", i, args, res.err, res.stderr)
		}
		cfg, err := loadConfig()
		if err != nil {
			t.Fatalf("loadConfig error = %v", err)
		}
		if len(cfg.Domains) != 1 {
			t.Fatalf("case %d (%v): domains = %+v, want exactly one (no duplicates)", i, args, cfg.Domains)
		}
		if cfg.Domains[0].Token != "tok" {
			t.Fatalf("case %d (%v): token = %q, want tok", i, args, cfg.Domains[0].Token)
		}
	}
}

func TestConfigSetConflictingTargets(t *testing.T) {
	home := aliasTestEnv(t)
	if res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://x.dev", "--no-install"); res.err != nil {
		t.Fatalf("alias add error = %v", res.err)
	}

	res := runAliasCLIStdin(t, "tok\n", "--alias", "xdev", "config", "set", "--server", "https://stage.dev", "--token-stdin")
	if res.err == nil {
		t.Fatal("conflicting targets should fail")
	}
	requireContains(t, res.err.Error(), "conflicting targets:", "error")
	requireContains(t, res.err.Error(), "--alias xdev → https://x.dev", "error")
	requireContains(t, res.err.Error(), "alias update xdev --server https://stage.dev", "error hint")
	requireNoFile(t, filepath.Join(home, ".ai-critic", "remote-agent-config.json"))

	res = runAliasCLIStdin(t, "tok\n", "config", "set", "--token-stdin")
	if res.err == nil {
		t.Fatal("missing target should fail")
	}
	requireContains(t, res.err.Error(), "config set needs a target", "error")

	res = runAliasCLIStdin(t, "tok\n", "--alias", "nope", "config", "set", "--token-stdin")
	if res.err == nil {
		t.Fatal("unknown alias should fail")
	}
	requireContains(t, res.err.Error(), `alias "nope" not found (available: xdev)`, "error")
}

func TestConfigSetTokenModeValidation(t *testing.T) {
	aliasTestEnv(t)
	cases := []struct {
		name  string
		stdin string
		args  []string
		want  string
	}{
		{
			name: "no mode",
			args: []string{"config", "set", "--server", "https://x.dev"},
			want: "config set requires --token, --token-stdin, --clear-token, or --default",
		},
		{
			name: "token and clear",
			args: []string{"config", "set", "--server", "https://x.dev", "--token", "t", "--clear-token"},
			want: "--token and --clear-token cannot be used together",
		},
		{
			name: "token and stdin",
			args: []string{"config", "set", "--server", "https://x.dev", "--token", "t", "--token-stdin"},
			want: "--token and --token-stdin cannot be used together",
		},
		{
			name: "stdin and clear",
			args: []string{"config", "set", "--server", "https://x.dev", "--token-stdin", "--clear-token"},
			want: "--token-stdin and --clear-token cannot be used together",
		},
		{
			name:  "empty stdin",
			stdin: "\n",
			args:  []string{"config", "set", "--server", "https://x.dev", "--token-stdin"},
			want:  "no token on stdin",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			res := runAliasCLIStdin(t, tc.stdin, tc.args...)
			if res.err == nil {
				t.Fatalf("expected error %q", tc.want)
			}
			requireContains(t, res.err.Error(), tc.want, "error")
		})
	}
}

func TestConfigSetDefaultOnlySwitchesDefault(t *testing.T) {
	aliasTestEnv(t)
	if res := runAliasCLIStdin(t, "def\n", "config", "set", "--server", "https://default.dev", "--token-stdin", "--default"); res.err != nil {
		t.Fatalf("config set default error = %v", res.err)
	}
	if res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://x.dev", "--no-install"); res.err != nil {
		t.Fatalf("alias add error = %v", res.err)
	}
	if res := runAliasCLIStdin(t, "xdev-token\n", "config", "set", "--alias", "xdev", "--token-stdin"); res.err != nil {
		t.Fatalf("config set via alias error = %v", res.err)
	}

	res := runAliasCLI(t, "--alias", "xdev", "config", "set", "--default")
	if res.err != nil {
		t.Fatalf("default-only set error = %v (stderr=%s)", res.err, res.stderr)
	}
	requireContains(t, res.stdout, "default domain set to https://x.dev", "stdout")
	if strings.Contains(res.stdout, "token set") {
		t.Fatalf("default-only set must not touch the token, got %q", res.stdout)
	}
	cfg, err := loadConfig()
	if err != nil {
		t.Fatalf("loadConfig error = %v", err)
	}
	if cfg.Default != "https://x.dev" {
		t.Fatalf("default = %q, want https://x.dev", cfg.Default)
	}
	if d := cfg.FindDomain("https://x.dev"); d == nil || d.Token != "xdev-token" {
		t.Fatalf("token must be preserved, domain = %+v", d)
	}

	// Default-only against an unknown domain is a clear error.
	res = runAliasCLI(t, "config", "set", "--server", "https://nowhere.dev", "--default")
	if res.err == nil {
		t.Fatal("default-only for a missing domain should fail")
	}
	requireContains(t, res.err.Error(), "no domain saved for https://nowhere.dev", "error")
}

func TestConfigSetClearTokenWarnsAboutAliases(t *testing.T) {
	aliasTestEnv(t)
	if res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://x.dev", "--no-install"); res.err != nil {
		t.Fatalf("alias add error = %v", res.err)
	}
	if res := runAliasCLIStdin(t, "tok\n", "config", "set", "--alias", "xdev", "--token-stdin"); res.err != nil {
		t.Fatalf("config set error = %v", res.err)
	}

	res := runAliasCLI(t, "config", "set", "--alias", "xdev", "--clear-token")
	if res.err != nil {
		t.Fatalf("clear-token error = %v", res.err)
	}
	requireContains(t, res.stdout, "token cleared for https://x.dev (aliases: xdev)", "stdout")
	requireContains(t, res.stderr, "warning: 1 alias uses this server: xdev", "stderr")
	cfg, err := loadConfig()
	if err != nil {
		t.Fatalf("loadConfig error = %v", err)
	}
	if d := cfg.FindDomain("https://x.dev"); d == nil || d.Token != "" {
		t.Fatalf("token should be cleared but domain kept, domain = %+v", d)
	}
}

func TestConfigSetDryRunWritesNothing(t *testing.T) {
	home := aliasTestEnv(t)
	if res := runAliasCLI(t, "alias", "add", "xdev", "--server", "https://x.dev", "--no-install"); res.err != nil {
		t.Fatalf("alias add error = %v", res.err)
	}
	res := runAliasCLIStdin(t, "tok\n", "config", "set", "--alias", "xdev", "--token-stdin", "--dry-run")
	if res.err != nil {
		t.Fatalf("dry-run error = %v", res.err)
	}
	requireContains(t, res.stdout, "[dry-run] would set token for https://x.dev (alias xdev)", "stdout")
	requireNoFile(t, filepath.Join(home, ".ai-critic", "remote-agent-config.json"))
}

func TestConfigSetRejectsArgvTokenWarning(t *testing.T) {
	aliasTestEnv(t)
	res := runAliasCLI(t, "config", "set", "--server", "https://x.dev", "--token", "s3cr3t")
	if res.err != nil {
		t.Fatalf("config set error = %v", res.err)
	}
	requireContains(t, res.stderr, "warning: --token is visible in shell history and ps; prefer --token-stdin", "stderr")
	if strings.Contains(res.stdout, "s3cr3t") || strings.Contains(res.stderr, "s3cr3t") {
		t.Fatal("config set must never echo the token")
	}
}

func TestConfigHelpMentionsSet(t *testing.T) {
	aliasTestEnv(t)
	res := runAliasCLI(t, "config", "--help")
	if res.err != nil {
		t.Fatalf("config --help error = %v", res.err)
	}
	for _, want := range []string{"config set [--server URL | --alias NAME]", "set       Add a domain"} {
		requireContains(t, res.stdout, want, "config help")
	}
	res = runAliasCLI(t, "config", "set", "--help")
	if res.err != nil {
		t.Fatalf("config set --help error = %v", res.err)
	}
	for _, want := range []string{"Target (first match wins", "--token-stdin", "--clear-token", "xdev-agent config set --token-stdin"} {
		requireContains(t, res.stdout, want, "config set help")
	}
}

func TestConfigRejectsUnknownSubcommand(t *testing.T) {
	aliasTestEnv(t)
	res := runAliasCLI(t, "config", "remove", "--server", "https://x.dev")
	if res.err == nil {
		t.Fatal("unknown config subcommand should fail")
	}
	requireContains(t, res.err.Error(), `unknown config subcommand "remove"`, "error")
}

func TestAliasHelpIsAvailable(t *testing.T) {
	aliasTestEnv(t)
	for _, args := range [][]string{
		{"alias", "--help"},
		{"alias", "list", "--help"},
		{"alias", "add", "--help"},
		{"alias", "update", "--help"},
		{"alias", "delete", "--help"},
		{"alias", "install", "--help"},
		{"alias", "which", "--help"},
	} {
		res := runAliasCLI(t, args...)
		if res.err != nil {
			t.Fatalf("%v error = %v", args, res.err)
		}
		requireContains(t, res.stdout, "Usage: remote-agent", "help stdout for "+strings.Join(args, " "))
	}
	res := runAliasCLI(t, "--help")
	if res.err != nil {
		t.Fatalf("root --help error = %v", res.err)
	}
	requireContains(t, res.stdout, "--alias NAME", "root help")
	requireContains(t, res.stdout, "alias                Named wrapper commands for other servers", "root help")
}

func TestFirstExecArg(t *testing.T) {
	cases := []struct {
		line string
		want string
		ok   bool
	}{
		{"exec remote-agent --alias xdev \"$@\"", "remote-agent", true},
		{"exec '/opt/my bin/remote-agent' --alias xdev \"$@\"", "/opt/my bin/remote-agent", true},
		{`exec '/opt/it'\''s/remote-agent' --alias x \"$@"`, "/opt/it's/remote-agent", true},
		{"echo hi", "", false},
		{"exec 'unterminated", "", false},
		{"exec ", "", false},
	}
	for _, tc := range cases {
		got, ok := firstExecArg(tc.line)
		if ok != tc.ok || got != tc.want {
			t.Fatalf("firstExecArg(%q) = (%q, %v), want (%q, %v)", tc.line, got, ok, tc.want, tc.ok)
		}
	}
}

func TestReadTokenStdin(t *testing.T) {
	got, err := readTokenStdin(strings.NewReader("tok-1\nignored\n"))
	if err != nil || got != "tok-1" {
		t.Fatalf("readTokenStdin = (%q, %v), want tok-1", got, err)
	}
	got, err = readTokenStdin(strings.NewReader("  tok-2  "))
	if err != nil || got != "tok-2" {
		t.Fatalf("readTokenStdin without newline = (%q, %v), want tok-2", got, err)
	}
	if _, err := readTokenStdin(strings.NewReader("\n\ntok\n")); err == nil {
		t.Fatal("empty first line should fail")
	}
}

func TestWrapperBodyAndOwnership(t *testing.T) {
	body := wrapperBody("remote-agent", "xdev")
	want := "#!/bin/sh\n" +
		"# generated by remote-agent alias install (alias: xdev); do not edit\n" +
		"exec remote-agent --alias xdev \"$@\"\n"
	if body != want {
		t.Fatalf("wrapperBody = %q, want %q", body, want)
	}
	if !isGeneratedWrapper(body) {
		t.Fatal("generated wrapper must be recognized")
	}
	if isGeneratedWrapper("#!/bin/sh\necho hi\n") {
		t.Fatal("user script must not be recognized as generated")
	}
	if got := wrapperExecBin(body); got != "remote-agent" {
		t.Fatalf("wrapperExecBin = %q, want remote-agent", got)
	}
}

func TestAliasServerArgValidation(t *testing.T) {
	if _, err := aliasServerArg("  "); err == nil {
		t.Fatal("empty server should fail")
	}
	if _, err := aliasServerArg("https://x.dev/a b"); err == nil {
		t.Fatal("whitespace in server should fail")
	}
	got, err := aliasServerArg(" https://x.dev/ ")
	if err != nil || got != "https://x.dev" {
		t.Fatalf("aliasServerArg = (%q, %v), want https://x.dev", got, err)
	}
}
