package agentcli

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/xhd2015/ai-critic/cmd/agentcli/testhooks"
	"github.com/xhd2015/dot-pkgs/go-pkgs/shell/localbin"
)

// aliasEntry is one named wrapper command that targets a specific server.
// Tokens are never stored here: `config set` owns credentials, and the alias
// server's token is read from the matching domain at resolve time.
type aliasEntry struct {
	Name   string `json:"name"`
	Binary string `json:"binary"`
	Server string `json:"server"`
}

// aliasStore is the persisted alias configuration (one file per profile).
type aliasStore struct {
	Version int          `json:"version"`
	Aliases []aliasEntry `json:"aliases"`
}

const aliasStoreVersion = 1

// wrapperMarkerPrefix marks wrapper scripts generated by `alias install`.
// A file carrying this marker is safe for alias commands to overwrite/remove;
// anything else is a user-owned script and is never touched without --force.
const wrapperMarkerPrefix = "# generated by remote-agent alias install (alias: "

// aliasNamePattern matches alias names and wrapper names: a plain,
// shell-friendly identifier (mirrors the ssh config-local host rule).
var aliasNamePattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]*$`)

// defaultWrapperSuffix derives a wrapper name from an alias name.
const defaultWrapperSuffix = "-agent"

// aliasStorePath returns ~/.ai-critic/<profile>-aliases.json. The alias store
// is deliberately separate from <profile>-config.json: the macOS app and the
// config web UI rewrite that file and would drop unknown fields.
func aliasStorePath() (string, error) {
	home, err := testhooks.UserHomeDir()
	if err != nil {
		return "", err
	}
	base := strings.TrimSuffix(active.ConfigFile, "-config.json")
	if base == "" || base == active.ConfigFile {
		base = strings.TrimSpace(active.Name)
	}
	if base == "" {
		base = "remote-agent"
	}
	return filepath.Join(home, ".ai-critic", base+"-aliases.json"), nil
}

// loadAliasStore reads the alias store. A missing file is an empty store.
func loadAliasStore() (*aliasStore, error) {
	path, err := aliasStorePath()
	if err != nil {
		return nil, err
	}
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return &aliasStore{Version: aliasStoreVersion, Aliases: []aliasEntry{}}, nil
		}
		return nil, err
	}
	var st aliasStore
	if err := json.Unmarshal(data, &st); err != nil {
		return nil, fmt.Errorf("failed to parse %s: %w", path, err)
	}
	if st.Aliases == nil {
		st.Aliases = []aliasEntry{}
	}
	return &st, nil
}

func saveAliasStore(st *aliasStore) error {
	path, err := aliasStorePath()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	out := *st
	out.Version = aliasStoreVersion
	if out.Aliases == nil {
		out.Aliases = []aliasEntry{}
	}
	data, err := json.MarshalIndent(&out, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0600)
}

// Find returns the alias with the given name, or nil.
func (st *aliasStore) Find(name string) *aliasEntry {
	if st == nil {
		return nil
	}
	for i := range st.Aliases {
		if st.Aliases[i].Name == name {
			return &st.Aliases[i]
		}
	}
	return nil
}

// FindByBinary returns the alias that owns the wrapper name, or nil.
func (st *aliasStore) FindByBinary(binary string) *aliasEntry {
	if st == nil {
		return nil
	}
	for i := range st.Aliases {
		if st.Aliases[i].Binary == binary {
			return &st.Aliases[i]
		}
	}
	return nil
}

// FindByServer returns every alias targeting server (trailing slashes ignored).
func (st *aliasStore) FindByServer(server string) []aliasEntry {
	if st == nil {
		return nil
	}
	server = normalizeServerForMatch(server)
	var out []aliasEntry
	for _, a := range st.Aliases {
		if normalizeServerForMatch(a.Server) == server {
			out = append(out, a)
		}
	}
	return out
}

// Names returns alias names sorted for stable output.
func (st *aliasStore) Names() []string {
	if st == nil {
		return nil
	}
	names := make([]string, 0, len(st.Aliases))
	for _, a := range st.Aliases {
		names = append(names, a.Name)
	}
	sort.Strings(names)
	return names
}

// Available renders the known alias names for "not found" errors.
func (st *aliasStore) Available() string {
	names := st.Names()
	if len(names) == 0 {
		return "none"
	}
	return strings.Join(names, ", ")
}

// Sorted returns aliases ordered by name.
func (st *aliasStore) Sorted() []aliasEntry {
	if st == nil {
		return nil
	}
	out := append([]aliasEntry(nil), st.Aliases...)
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func validateAliasName(name string) error {
	if !aliasNamePattern.MatchString(name) {
		return fmt.Errorf("invalid alias name %q: use letters, digits, dot, dash, underscore", name)
	}
	return nil
}

func validateAliasBinary(binary string) error {
	if !aliasNamePattern.MatchString(binary) {
		return fmt.Errorf("invalid wrapper name %q: use letters, digits, dot, dash, underscore", binary)
	}
	switch binary {
	case "remote-agent", "local-agent":
		return fmt.Errorf("--binary %s would shadow the %s CLI itself", binary, binary)
	}
	return nil
}

// aliasServerArg validates and normalizes a --server value.
func aliasServerArg(server string) (string, error) {
	server = strings.TrimSpace(server)
	if server == "" {
		return "", fmt.Errorf("--server is required")
	}
	if strings.ContainsAny(server, " \t\n") {
		return "", fmt.Errorf("invalid server %q: whitespace is not allowed", server)
	}
	return normalizeServerForMatch(server), nil
}

// wrapperMarker identifies one generated wrapper inside its own body.
func wrapperMarker(name string) string {
	return wrapperMarkerPrefix + name + "); do not edit"
}

// wrapperBody renders the generated wrapper: #!/bin/sh, an ownership marker,
// then a forwarder that re-enters the CLI through --alias.
func wrapperBody(bin, name string) string {
	execLine := strings.TrimPrefix(localbin.ForwarderBody([]string{bin, "--alias", name}), "#!/bin/sh\n")
	return "#!/bin/sh\n" + wrapperMarker(name) + "\n" + execLine
}

// isGeneratedWrapper reports whether content was written by `alias install`.
func isGeneratedWrapper(content string) bool {
	return strings.Contains(content, wrapperMarkerPrefix)
}

// firstExecArg returns argv[0] of a shell `exec …` line as produced by
// localbin.ForwarderBody's quoting. ok is false when the line cannot be read.
func firstExecArg(line string) (arg string, ok bool) {
	rest, found := strings.CutPrefix(line, "exec ")
	if !found || rest == "" {
		return "", false
	}
	if rest[0] != '\'' {
		// shellQuote leaves safe words bare.
		if i := strings.IndexAny(rest, " \t"); i >= 0 {
			return rest[:i], true
		}
		return rest, true
	}
	// Single-quoted word: shellQuote escapes an embedded quote as '\''.
	var b strings.Builder
	for i := 1; i < len(rest); {
		if rest[i] != '\'' {
			b.WriteByte(rest[i])
			i++
			continue
		}
		if strings.HasPrefix(rest[i:], `'\''`) {
			b.WriteByte('\'')
			i += 4
			continue
		}
		return b.String(), true
	}
	return "", false
}

// wrapperExecBin returns the binary a generated wrapper execs, or "".
func wrapperExecBin(content string) string {
	for _, line := range strings.Split(content, "\n") {
		if !strings.HasPrefix(line, "exec ") {
			continue
		}
		if arg, ok := firstExecArg(line); ok {
			return arg
		}
		return ""
	}
	return ""
}

// defaultWrapperBin resolves what a generated wrapper should exec: the
// remote-agent on PATH when present (survives upgrades/reinstalls), else this
// binary's absolute path. warning is non-empty when the fallback was needed.
func defaultWrapperBin() (bin string, warning string) {
	if p, err := exec.LookPath("remote-agent"); err == nil && strings.TrimSpace(p) != "" {
		return "remote-agent", ""
	}
	exe, err := os.Executable()
	if err != nil || strings.TrimSpace(exe) == "" {
		return "remote-agent",
			"remote-agent not found on PATH; wrapper execs 'remote-agent' (install it before use)"
	}
	return exe, fmt.Sprintf("remote-agent not found on PATH; wrapper execs %s", exe)
}

// wrapperTarget is the effective exec target for an alias: what its installed
// wrapper execs when readable, else the default resolution.
func wrapperTarget(binDir string, a aliasEntry) (bin string, warning string) {
	content, err := os.ReadFile(filepath.Join(binDir, a.Binary))
	if err == nil && isGeneratedWrapper(string(content)) {
		if bin := wrapperExecBin(string(content)); bin != "" {
			return bin, ""
		}
	}
	return defaultWrapperBin()
}

// displayHomePath renders abs as ~/… when it lives under home.
func displayHomePath(home, abs string) string {
	home = filepath.Clean(home)
	abs = filepath.Clean(abs)
	if home != "" && home != "." && (abs == home || strings.HasPrefix(abs, home+string(os.PathSeparator))) {
		return "~" + abs[len(home):]
	}
	return abs
}

// aliasTokenState reports whether a token is saved for server.
func aliasTokenState(cfg *agentConfig, server string) (state string, ok bool) {
	if cfg != nil {
		if d := cfg.FindDomain(server); d != nil && strings.TrimSpace(d.Token) != "" {
			return "set", true
		}
	}
	return "missing", false
}

// aliasBinDir returns ~/.local/bin for the effective home.
func aliasBinDir() (dir string, home string, err error) {
	home, err = testhooks.UserHomeDir()
	if err != nil {
		return "", "", err
	}
	dir, err = localbin.DefaultDir(home)
	if err != nil {
		return "", "", err
	}
	return dir, home, nil
}
