package agentcli

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/tabwriter"

	"github.com/xhd2015/dot-pkgs/go-pkgs/shell/localbin"
	"github.com/xhd2015/less-gen/flags"
)

const aliasHelp = `Usage: remote-agent alias <subcommand> [args...]

Create thin wrapper commands (for example xdev-agent) that run remote-agent
against a different ai-critic server than the default one.

Subcommands:
  list                 List aliases and whether their wrapper is installed
  add <name>           Record an alias and install its wrapper
  update <name>        Change an alias's server, wrapper name, or exec target
  delete <name>        Remove an alias (and its wrapper when we generated it)
  install [<name>...]  (Re)write wrapper scripts into ~/.local/bin
  which [<name>]       Show where an alias points and how it is installed

Aliases are stored in ~/.ai-critic/remote-agent-aliases.json; wrappers live in
~/.local/bin and exec: remote-agent --alias <name> "$@"

Tokens belong to servers, not aliases. Set one with:
  <name>-agent config set --token-stdin

Run 'remote-agent alias <subcommand> --help' for options.
`

const aliasListHelp = `Usage: remote-agent alias list [--json]

List aliases with their wrapper path and whether a token is saved for the
alias's server.

Options:
  --json          Print machine-readable JSON
  -h, --help      Show this help message
`

const aliasAddHelp = `Usage: remote-agent alias add <name> --server URL [options]

Record an alias and install its wrapper script into ~/.local/bin.

Options:
  --server URL    Server base URL the wrapper targets (required)
  --binary NAME   Wrapper file name (default: <name>-agent)
  --bin PATH      remote-agent binary the wrapper execs
                  (default: remote-agent on PATH, else this binary)
  --no-install    Record the alias only; do not write the wrapper
  --force         Overwrite an existing file at the wrapper path
  --dry-run       Print the plan; write nothing
  -h, --help      Show this help message

Tokens are stored per server, so set one after adding the alias:
  <name>-agent config set --token-stdin

Examples:
  remote-agent alias add xdev --server https://agent-xdev-aes562.xhd2015.xyz
  remote-agent alias add xdev --server http://10.0.0.9:23712 --binary xdev
`

const aliasUpdateHelp = `Usage: remote-agent alias update <name> [options]

Change an alias's server, wrapper file name, or wrapper exec target. The
wrapper body never embeds the server, so a server change needs no rewrite.

Options:
  --server URL    New server base URL
  --binary NAME   New wrapper file name (renames the wrapper file)
  --bin PATH      New remote-agent binary the wrapper execs
  --force         Overwrite an existing file at the wrapper path
  --dry-run       Print the plan; write nothing
  -h, --help      Show this help message

To change a token, target the alias's server:
  <name>-agent config set --token-stdin
`

const aliasDeleteHelp = `Usage: remote-agent alias delete <name> [options]
       remote-agent alias remove <name> [options]

Remove an alias. Its wrapper is removed only when generated by this command;
a user-owned file at that path is left in place with a warning.

Options:
  --keep-wrapper  Remove the alias record only; keep the wrapper file
  --dry-run       Print the plan; write nothing
  -h, --help      Show this help message
`

const aliasInstallHelp = `Usage: remote-agent alias install [<name>...] [options]
       remote-agent alias install --all [options]

(Re)write wrapper scripts into ~/.local/bin and make sure that directory is on
PATH. Existing wrappers with identical content are left untouched.

Options:
  --all           Install every recorded alias
  --bin PATH      remote-agent binary the wrappers exec
                  (default: remote-agent on PATH, else this binary)
  --force         Overwrite files not generated by this command
  --dry-run       Print the plan; write nothing
  -h, --help      Show this help message

Examples:
  remote-agent alias install --all
  remote-agent alias install xdev
`

const aliasWhichHelp = `Usage: remote-agent alias which [<name|binary>] [--json]

Show where an alias points and how its wrapper is installed. The name may be
an alias name or a wrapper file name; with no argument the alias selected by
the global --alias flag is used.

Options:
  --json          Print machine-readable JSON
  -h, --help      Show this help message
`

// runAlias handles the remote-agent `alias` command. globalAlias is the value
// of the global --alias flag, which `which` falls back to.
func runAlias(args []string, stdout, stderr io.Writer, globalAlias string) error {
	if stdout == nil {
		stdout = os.Stdout
	}
	if stderr == nil {
		stderr = os.Stderr
	}
	if len(args) == 0 || isHelpArg(args[0]) {
		fmt.Fprint(stdout, aliasHelp)
		return nil
	}
	sub, rest := args[0], args[1:]
	switch sub {
	case "list":
		return runAliasList(rest, stdout)
	case "add":
		return runAliasAdd(rest, stdout, stderr)
	case "update":
		return runAliasUpdate(rest, stdout, stderr)
	case "delete", "remove":
		return runAliasDelete(rest, stdout, stderr)
	case "install":
		return runAliasInstall(rest, stdout, stderr)
	case "which":
		return runAliasWhich(rest, stdout, stderr, globalAlias)
	default:
		return fmt.Errorf("unknown alias subcommand %q; see '%s alias --help'", sub, active.Name)
	}
}

func isHelpArg(arg string) bool {
	return arg == "-h" || arg == "--help"
}

// aliasListEntryJSON is the --json shape of `alias list`.
type aliasListEntryJSON struct {
	Name      string `json:"name"`
	Binary    string `json:"binary"`
	Server    string `json:"server"`
	Installed bool   `json:"installed"`
	TokenSet  bool   `json:"token_set"`
}

func runAliasList(args []string, stdout io.Writer) error {
	var asJSON bool
	args, err := flags.
		Bool("--json", &asJSON).
		HelpFunc("-h,--help", func() { fmt.Fprint(stdout, aliasListHelp) }).
		HelpNoExit().
		Parse(args)
	if err != nil {
		if errors.Is(err, flags.ErrHelp) {
			return nil
		}
		return err
	}
	if len(args) > 0 {
		return fmt.Errorf("alias list takes no arguments, got %v; see '%s alias list --help'", args, active.Name)
	}

	store, err := loadAliasStore()
	if err != nil {
		return err
	}
	cfg, err := loadConfig()
	if err != nil {
		return err
	}
	binDir, home, err := aliasBinDir()
	if err != nil {
		return err
	}

	if asJSON {
		out := struct {
			Aliases []aliasListEntryJSON `json:"aliases"`
		}{Aliases: []aliasListEntryJSON{}}
		for _, a := range store.Sorted() {
			path := filepath.Join(binDir, a.Binary)
			_, statErr := os.Stat(path)
			_, tokenSet := aliasTokenState(cfg, a.Server)
			out.Aliases = append(out.Aliases, aliasListEntryJSON{
				Name:      a.Name,
				Binary:    a.Binary,
				Server:    a.Server,
				Installed: statErr == nil,
				TokenSet:  tokenSet,
			})
		}
		return json.NewEncoder(stdout).Encode(out)
	}

	if len(store.Aliases) == 0 {
		fmt.Fprintln(stdout, "no aliases")
		fmt.Fprintln(stdout)
		fmt.Fprintln(stdout, "Add one with:")
		fmt.Fprintf(stdout, "  %s alias add xdev --server https://agent-xdev.example.com\n", active.Name)
		return nil
	}

	tw := tabwriter.NewWriter(stdout, 0, 4, 2, ' ', 0)
	fmt.Fprintln(tw, "NAME\tBINARY\tINSTALLED\tSERVER\tTOKEN")
	for _, a := range store.Sorted() {
		fmt.Fprintf(tw, "%s\t%s\t%s\t%s\t%s\n",
			a.Name, a.Binary, aliasInstalledCell(binDir, home, a), a.Server, aliasTokenCell(cfg, a.Server))
	}
	if err := tw.Flush(); err != nil {
		return err
	}
	fmt.Fprintln(stdout)
	fmt.Fprintf(stdout, "%d %s\n", len(store.Aliases), pluralAliases(len(store.Aliases)))
	return nil
}

func aliasInstalledCell(binDir, home string, a aliasEntry) string {
	path := filepath.Join(binDir, a.Binary)
	content, err := os.ReadFile(path)
	if err != nil {
		return "-"
	}
	cell := displayHomePath(home, path)
	if !isGeneratedWrapper(string(content)) {
		cell += " (foreign)"
	}
	return cell
}

func aliasTokenCell(cfg *agentConfig, server string) string {
	state, _ := aliasTokenState(cfg, server)
	return state
}

func pluralAliases(n int) string {
	if n == 1 {
		return "alias"
	}
	return "aliases"
}

func runAliasAdd(args []string, stdout, stderr io.Writer) error {
	var serverFlag, binaryFlag, binFlag string
	var noInstall, force, dryRun bool
	args, err := flags.
		String("--server", &serverFlag).
		String("--binary", &binaryFlag).
		String("--bin", &binFlag).
		Bool("--no-install", &noInstall).
		Bool("--force", &force).
		Bool("--dry-run", &dryRun).
		HelpFunc("-h,--help", func() { fmt.Fprint(stdout, aliasAddHelp) }).
		HelpNoExit().
		Parse(args)
	if err != nil {
		if errors.Is(err, flags.ErrHelp) {
			return nil
		}
		return err
	}
	if len(args) != 1 {
		return fmt.Errorf("alias add requires <name>; see '%s alias add --help'", active.Name)
	}
	name := strings.TrimSpace(args[0])
	if err := validateAliasName(name); err != nil {
		return err
	}
	binary := strings.TrimSpace(binaryFlag)
	if binary == "" {
		binary = name + defaultWrapperSuffix
	}
	if err := validateAliasBinary(binary); err != nil {
		return err
	}
	server, err := aliasServerArg(serverFlag)
	if err != nil {
		return err
	}

	store, err := loadAliasStore()
	if err != nil {
		return err
	}
	if store.Find(name) != nil {
		return fmt.Errorf("alias %q already exists; use '%s alias update %s' to change it", name, active.Name, name)
	}
	if other := store.FindByBinary(binary); other != nil {
		return fmt.Errorf("wrapper name %q is already used by alias %q; pass --binary", binary, other.Name)
	}

	binDir, home, err := aliasBinDir()
	if err != nil {
		return err
	}
	path := filepath.Join(binDir, binary)
	display := displayHomePath(home, path)
	content, readErr := os.ReadFile(path)
	exists := readErr == nil
	generated := exists && isGeneratedWrapper(string(content))

	entry := aliasEntry{Name: name, Binary: binary, Server: server}
	if !noInstall && exists && !generated && !force {
		return fmt.Errorf("%s exists and was not generated by %s alias; pass --force", display, active.Name)
	}

	bin, binWarn := resolveAliasBin(binFlag)
	body := wrapperBody(bin, name)

	if dryRun {
		fmt.Fprintf(stdout, "[dry-run] would add alias %s → %s\n", name, server)
		if noInstall {
			fmt.Fprintln(stdout, "[dry-run] would skip the wrapper (--no-install)")
		} else {
			printWrapperDryRun(stdout, display, exists, generated, string(content), body)
			ensureLocalBinPATH(home, binDir, true, stdout, stderr)
		}
		printAliasBinWarning(stderr, binWarn)
		printAliasTokenWarning(stderr, entry)
		return nil
	}

	store.Aliases = append(store.Aliases, entry)
	if err := saveAliasStore(store); err != nil {
		return err
	}

	printAliasBinWarning(stderr, binWarn)
	if noInstall {
		fmt.Fprintf(stdout, "added alias %s → %s (no wrapper)\n", name, server)
	} else {
		if _, err := installWrapper(binDir, home, entry, bin, force, false, stdout, stderr); err != nil {
			return err
		}
		ensureLocalBinPATH(home, binDir, false, stdout, stderr)
	}
	printAliasTokenWarning(stderr, entry)
	return nil
}

func runAliasUpdate(args []string, stdout, stderr io.Writer) error {
	var serverFlag, binaryFlag, binFlag string
	var force, dryRun bool
	args, err := flags.
		String("--server", &serverFlag).
		String("--binary", &binaryFlag).
		String("--bin", &binFlag).
		Bool("--force", &force).
		Bool("--dry-run", &dryRun).
		HelpFunc("-h,--help", func() { fmt.Fprint(stdout, aliasUpdateHelp) }).
		HelpNoExit().
		Parse(args)
	if err != nil {
		if errors.Is(err, flags.ErrHelp) {
			return nil
		}
		return err
	}
	if len(args) != 1 {
		return fmt.Errorf("alias update requires <name>; see '%s alias update --help'", active.Name)
	}
	name := strings.TrimSpace(args[0])

	store, err := loadAliasStore()
	if err != nil {
		return err
	}
	entry := store.Find(name)
	if entry == nil {
		return aliasNotFound(name, store)
	}
	previous := *entry
	updated := *entry

	if strings.TrimSpace(serverFlag) != "" {
		server, err := aliasServerArg(serverFlag)
		if err != nil {
			return err
		}
		updated.Server = server
	}
	if strings.TrimSpace(binaryFlag) != "" {
		binary := strings.TrimSpace(binaryFlag)
		if err := validateAliasBinary(binary); err != nil {
			return err
		}
		if binary != updated.Binary {
			if other := store.FindByBinary(binary); other != nil && other.Name != name {
				return fmt.Errorf("wrapper name %q is already used by alias %q", binary, other.Name)
			}
			updated.Binary = binary
		}
	}

	binDir, home, err := aliasBinDir()
	if err != nil {
		return err
	}
	newPath := filepath.Join(binDir, updated.Binary)
	newDisplay := displayHomePath(home, newPath)
	content, readErr := os.ReadFile(newPath)
	newExists := readErr == nil
	newGenerated := newExists && isGeneratedWrapper(string(content))
	if newExists && !newGenerated && !force {
		return fmt.Errorf("%s exists and was not generated by %s alias; pass --force", newDisplay, active.Name)
	}

	serverChanged := updated.Server != previous.Server
	binaryChanged := updated.Binary != previous.Binary
	// The wrapper is only written when the exec target or the file name
	// changes. A rename keeps the recorded exec target instead of silently
	// re-resolving it; `alias install` is the explicit repair path.
	binChanged := strings.TrimSpace(binFlag) != ""
	writeWrapper := binaryChanged || binChanged
	var bin, binWarn string
	switch {
	case binChanged:
		bin, binWarn = resolveAliasBin(binFlag)
	case binaryChanged:
		bin = previousWrapperBin(binDir, previous)
		if bin == "" {
			bin, binWarn = defaultWrapperBin()
		}
	}

	if !serverChanged && !binaryChanged && !binChanged {
		if dryRun {
			fmt.Fprintf(stdout, "[dry-run] alias %s unchanged\n", name)
			return nil
		}
		fmt.Fprintf(stdout, "alias %s unchanged\n", name)
		return nil
	}

	if dryRun {
		if serverChanged {
			fmt.Fprintf(stdout, "[dry-run] would update alias %s (server: %s → %s)\n", name, previous.Server, updated.Server)
		}
		if binaryChanged {
			fmt.Fprintf(stdout, "[dry-run] would update alias %s (binary: %s → %s)\n", name, previous.Binary, updated.Binary)
		}
		if writeWrapper {
			printWrapperDryRun(stdout, newDisplay, newExists, newGenerated, string(content), wrapperBody(bin, name))
		}
		if binaryChanged {
			printWrapperRemovalDryRun(stdout, stderr, binDir, home, previous)
		}
		printAliasBinWarning(stderr, binWarn)
		if serverChanged {
			printAliasTokenWarning(stderr, updated)
		}
		return nil
	}

	*entry = updated
	if err := saveAliasStore(store); err != nil {
		return err
	}
	if serverChanged {
		fmt.Fprintf(stdout, "updated alias %s (server: %s → %s)\n", name, previous.Server, updated.Server)
	}
	if binaryChanged {
		fmt.Fprintf(stdout, "updated alias %s (binary: %s → %s)\n", name, previous.Binary, updated.Binary)
	}

	printAliasBinWarning(stderr, binWarn)
	if writeWrapper {
		if _, err := installWrapper(binDir, home, updated, bin, force, false, stdout, stderr); err != nil {
			return err
		}
	}
	if binaryChanged {
		if err := removeWrapperIfGenerated(binDir, home, previous, stdout, stderr); err != nil {
			return err
		}
	}
	if serverChanged {
		printAliasTokenWarning(stderr, updated)
	}
	return nil
}

// previousWrapperBin returns the exec target recorded in an existing generated
// wrapper, or "" when it is missing or unreadable.
func previousWrapperBin(binDir string, a aliasEntry) string {
	content, err := os.ReadFile(filepath.Join(binDir, a.Binary))
	if err != nil || !isGeneratedWrapper(string(content)) {
		return ""
	}
	return wrapperExecBin(string(content))
}

func runAliasDelete(args []string, stdout, stderr io.Writer) error {
	var keepWrapper, dryRun bool
	args, err := flags.
		Bool("--keep-wrapper", &keepWrapper).
		Bool("--dry-run", &dryRun).
		HelpFunc("-h,--help", func() { fmt.Fprint(stdout, aliasDeleteHelp) }).
		HelpNoExit().
		Parse(args)
	if err != nil {
		if errors.Is(err, flags.ErrHelp) {
			return nil
		}
		return err
	}
	if len(args) != 1 {
		return fmt.Errorf("alias delete requires <name>; see '%s alias delete --help'", active.Name)
	}
	name := strings.TrimSpace(args[0])

	store, err := loadAliasStore()
	if err != nil {
		return err
	}
	entry := store.Find(name)
	if entry == nil {
		return aliasNotFound(name, store)
	}
	binDir, home, err := aliasBinDir()
	if err != nil {
		return err
	}

	if dryRun {
		fmt.Fprintf(stdout, "[dry-run] would remove alias %s\n", name)
		if !keepWrapper {
			printWrapperRemovalDryRun(stdout, stderr, binDir, home, *entry)
		}
		return nil
	}

	kept := make([]aliasEntry, 0, len(store.Aliases))
	for _, a := range store.Aliases {
		if a.Name != name {
			kept = append(kept, a)
		}
	}
	store.Aliases = kept
	if err := saveAliasStore(store); err != nil {
		return err
	}
	fmt.Fprintf(stdout, "removed alias %s\n", name)
	if keepWrapper {
		return nil
	}
	return removeWrapperIfGenerated(binDir, home, *entry, stdout, stderr)
}

func runAliasInstall(args []string, stdout, stderr io.Writer) error {
	var all, force, dryRun bool
	var binFlag string
	args, err := flags.
		Bool("--all", &all).
		Bool("--force", &force).
		Bool("--dry-run", &dryRun).
		String("--bin", &binFlag).
		HelpFunc("-h,--help", func() { fmt.Fprint(stdout, aliasInstallHelp) }).
		HelpNoExit().
		Parse(args)
	if err != nil {
		if errors.Is(err, flags.ErrHelp) {
			return nil
		}
		return err
	}
	if all && len(args) > 0 {
		return fmt.Errorf("alias install takes either <name>... or --all; see '%s alias install --help'", active.Name)
	}
	if !all && len(args) == 0 {
		return fmt.Errorf("alias install needs <name>... or --all; see '%s alias install --help'", active.Name)
	}

	store, err := loadAliasStore()
	if err != nil {
		return err
	}
	var targets []aliasEntry
	if all {
		targets = store.Sorted()
	} else {
		for _, name := range args {
			name = strings.TrimSpace(name)
			entry := store.Find(name)
			if entry == nil {
				return aliasNotFound(name, store)
			}
			targets = append(targets, *entry)
		}
	}
	if len(targets) == 0 {
		fmt.Fprintln(stdout, "no aliases")
		return nil
	}

	binDir, home, err := aliasBinDir()
	if err != nil {
		return err
	}
	bin, binWarn := resolveAliasBin(binFlag)
	printAliasBinWarning(stderr, binWarn)
	for _, a := range targets {
		if _, err := installWrapper(binDir, home, a, bin, force, dryRun, stdout, stderr); err != nil {
			return err
		}
	}
	ensureLocalBinPATH(home, binDir, dryRun, stdout, stderr)
	return nil
}

// aliasWhichJSON is the --json shape of `alias which`.
type aliasWhichJSON struct {
	Name      string `json:"name"`
	Binary    string `json:"binary"`
	Path      string `json:"path"`
	Installed bool   `json:"installed"`
	Identical bool   `json:"identical"`
	Server    string `json:"server"`
	TokenSet  bool   `json:"token_set"`
	Exec      string `json:"exec"`
}

func runAliasWhich(args []string, stdout, stderr io.Writer, globalAlias string) error {
	var asJSON bool
	args, err := flags.
		Bool("--json", &asJSON).
		HelpFunc("-h,--help", func() { fmt.Fprint(stdout, aliasWhichHelp) }).
		HelpNoExit().
		Parse(args)
	if err != nil {
		if errors.Is(err, flags.ErrHelp) {
			return nil
		}
		return err
	}
	if len(args) > 1 {
		return fmt.Errorf("alias which takes at most one <name|binary>, got %v; see '%s alias which --help'", args, active.Name)
	}

	store, err := loadAliasStore()
	if err != nil {
		return err
	}
	var entry *aliasEntry
	switch {
	case len(args) == 1:
		ref := strings.TrimSpace(args[0])
		entry = store.Find(ref)
		if entry == nil {
			entry = store.FindByBinary(ref)
		}
		if entry == nil {
			return aliasNotFound(ref, store)
		}
	case globalAlias != "":
		entry = store.Find(globalAlias)
		if entry == nil {
			return fmt.Errorf("unknown alias %q (available: %s); run '%s alias list'", globalAlias, store.Available(), active.Name)
		}
	default:
		return fmt.Errorf("alias which needs <name|binary>; see '%s alias which --help'", active.Name)
	}

	cfg, err := loadConfig()
	if err != nil {
		return err
	}
	binDir, home, err := aliasBinDir()
	if err != nil {
		return err
	}

	path := filepath.Join(binDir, entry.Binary)
	content, readErr := os.ReadFile(path)
	installed := readErr == nil
	encoded := string(content)
	identical := false
	state := "missing"
	execBin := ""
	if installed {
		switch {
		case !isGeneratedWrapper(encoded):
			state = "foreign"
			execBin, _ = defaultWrapperBin()
		default:
			execBin = wrapperExecBin(encoded)
			if execBin != "" && encoded == wrapperBody(execBin, entry.Name) {
				state = "installed"
				identical = true
			} else {
				state = "stale"
			}
			if execBin == "" {
				execBin, _ = defaultWrapperBin()
			}
		}
	} else {
		execBin, _ = defaultWrapperBin()
	}
	tokenState, tokenSet := aliasTokenState(cfg, entry.Server)

	if asJSON {
		return json.NewEncoder(stdout).Encode(aliasWhichJSON{
			Name:      entry.Name,
			Binary:    entry.Binary,
			Path:      path,
			Installed: installed,
			Identical: identical,
			Server:    entry.Server,
			TokenSet:  tokenSet,
			Exec:      execBin + " --alias " + entry.Name,
		})
	}

	tw := tabwriter.NewWriter(stdout, 0, 4, 3, ' ', 0)
	fmt.Fprintf(tw, "alias\t%s\n", entry.Name)
	fmt.Fprintf(tw, "binary\t%s (%s)\n", displayHomePath(home, path), state)
	fmt.Fprintf(tw, "server\t%s\n", entry.Server)
	fmt.Fprintf(tw, "token\tdomain (%s)\n", tokenState)
	fmt.Fprintf(tw, "exec\t%s --alias %s\n", execBin, entry.Name)
	if !tokenSet {
		fmt.Fprintf(tw, "hint\tset it with: %s config set --token-stdin\n", entry.Binary)
	}
	if state == "stale" {
		fmt.Fprintf(tw, "hint\trun '%s alias install %s' to refresh the wrapper\n", active.Name, entry.Name)
	}
	return tw.Flush()
}

// resolveAliasBin resolves the wrapper exec target from --bin or the default.
func resolveAliasBin(binFlag string) (bin, warning string) {
	binFlag = strings.TrimSpace(binFlag)
	if binFlag == "" {
		return defaultWrapperBin()
	}
	if strings.ContainsRune(binFlag, os.PathSeparator) {
		if _, err := os.Stat(binFlag); err != nil {
			return binFlag, fmt.Sprintf("--bin %s does not exist", binFlag)
		}
		return binFlag, ""
	}
	if _, err := exec.LookPath(binFlag); err != nil {
		return binFlag, fmt.Sprintf("--bin %s not found on PATH", binFlag)
	}
	return binFlag, ""
}

func printAliasBinWarning(stderr io.Writer, warning string) {
	if warning != "" {
		fmt.Fprintf(stderr, "warning: %s\n", warning)
	}
}

// printAliasTokenWarning tells the user how to fix a missing token for the
// server an alias targets.
func printAliasTokenWarning(stderr io.Writer, a aliasEntry) {
	cfg, err := loadConfig()
	if err != nil {
		return
	}
	if _, ok := aliasTokenState(cfg, a.Server); ok {
		return
	}
	fmt.Fprintf(stderr, "warning: no token saved for %s; set one with:\n  %s config set --token-stdin\n", a.Server, a.Binary)
}

// installWrapper writes (or refreshes) one wrapper and prints the result.
// A file that is not a generated wrapper is skipped with a warning unless
// force is set. Returns true when the file was written.
func installWrapper(binDir, home string, a aliasEntry, bin string, force, dryRun bool, stdout, stderr io.Writer) (bool, error) {
	path := filepath.Join(binDir, a.Binary)
	display := displayHomePath(home, path)
	body := wrapperBody(bin, a.Name)
	content, readErr := os.ReadFile(path)
	exists := readErr == nil

	switch {
	case exists && string(content) == body:
		if dryRun {
			fmt.Fprintf(stdout, "[dry-run] skip: %s (already identical)\n", display)
		}
		return false, nil
	case exists && !isGeneratedWrapper(string(content)):
		if !force {
			fmt.Fprintf(stderr, "warning: %s exists and was not generated by %s alias; skipped (use --force)\n", display, active.Name)
			return false, nil
		}
		if dryRun {
			fmt.Fprintf(stdout, "[dry-run] would overwrite %s (not generated by %s alias)\n", display, active.Name)
			return false, nil
		}
		fmt.Fprintf(stderr, "warning: replaced %s (was not generated by %s alias)\n", display, active.Name)
	case dryRun:
		fmt.Fprintf(stdout, "[dry-run] would write %s\n", display)
		return false, nil
	}

	if _, err := localbin.WriteScript(binDir, a.Binary, body); err != nil {
		return false, fmt.Errorf("write wrapper: %w", err)
	}
	fmt.Fprintf(stdout, "installed %s (alias %s → %s)\n", display, a.Name, a.Server)
	return true, nil
}

func printWrapperDryRun(stdout io.Writer, display string, exists, generated bool, content, body string) {
	switch {
	case exists && content == body:
		fmt.Fprintf(stdout, "[dry-run] skip: %s (already identical)\n", display)
	case exists && !generated:
		fmt.Fprintf(stdout, "[dry-run] would overwrite %s (not generated by %s alias)\n", display, active.Name)
	default:
		fmt.Fprintf(stdout, "[dry-run] would write %s\n", display)
	}
}

// removeWrapperIfGenerated removes a wrapper file only when it carries the
// generated marker; anything else is reported and left alone.
func removeWrapperIfGenerated(binDir, home string, a aliasEntry, stdout, stderr io.Writer) error {
	path := filepath.Join(binDir, a.Binary)
	display := displayHomePath(home, path)
	content, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if !isGeneratedWrapper(string(content)) {
		fmt.Fprintf(stderr, "warning: not removing %s (not generated by %s alias)\n", display, active.Name)
		return nil
	}
	if err := os.Remove(path); err != nil {
		return fmt.Errorf("remove %s: %w", display, err)
	}
	fmt.Fprintf(stdout, "removed %s\n", display)
	return nil
}

func printWrapperRemovalDryRun(stdout, stderr io.Writer, binDir, home string, a aliasEntry) {
	path := filepath.Join(binDir, a.Binary)
	display := displayHomePath(home, path)
	content, err := os.ReadFile(path)
	if err != nil {
		return
	}
	if !isGeneratedWrapper(string(content)) {
		fmt.Fprintf(stderr, "warning: not removing %s (not generated by %s alias)\n", display, active.Name)
		return
	}
	fmt.Fprintf(stdout, "[dry-run] would remove %s\n", display)
}

// ensureLocalBinPATH makes ~/.local/bin reachable from bash/zsh rc files.
// EnsureOnPATH reports problems on stderr and never fails the install.
func ensureLocalBinPATH(home, binDir string, dryRun bool, stdout, stderr io.Writer) {
	localbin.EnsureOnPATH(localbin.EnsureOpts{
		Home:    home,
		DestDir: binDir,
		DryRun:  dryRun,
		Stdout:  stdout,
		Stderr:  stderr,
	})
}

// aliasNotFound renders the standard unknown-alias error.
func aliasNotFound(ref string, store *aliasStore) error {
	return fmt.Errorf("alias %q not found (available: %s); run '%s alias list'", ref, store.Available(), active.Name)
}
