package sshcmd

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

// ServeService owns the local serve lifecycle: relay + session file + ssh_config.
type ServeService struct {
	Store     *FileSessionStore
	ProfileID string
	Dial      DialFunc
	User      string
	ConfigDir string
	ServePID  int
}

// Start listens, saves an Alive session, blocks until ctx is canceled, then
// clears the session and closes the relay. Nil Dial fails before listen.
func (s *ServeService) Start(ctx context.Context) error {
	if s == nil {
		return errors.New("ServeService is nil")
	}
	if s.Dial == nil {
		return errors.New("dial not configured: Dial is required")
	}
	if s.Store == nil {
		return errors.New("session store not configured")
	}
	profileID := s.ProfileID
	if profileID == "" {
		profileID = "default"
	}
	user := s.User
	if user == "" {
		user = "agent"
	}

	relay := &LocalRelay{Dial: s.Dial}
	if err := relay.Start(); err != nil {
		return err
	}
	// Always close relay on exit (cancel path and error path after Start).
	defer func() { _ = relay.Close() }()

	port := relay.LocalPort()
	if port <= 0 {
		return errors.New("relay did not bind a local port")
	}

	if s.ConfigDir != "" {
		if err := os.MkdirAll(s.ConfigDir, 0o755); err != nil {
			return err
		}
		if err := writeSSHConfig(s.ConfigDir, user, port); err != nil {
			return err
		}
	}

	sess := &Session{
		LocalPort: port,
		User:      user,
		ConfigDir: s.ConfigDir,
		ServePID:  s.ServePID,
		ProfileID: profileID,
		Alive:     true,
	}
	if err := s.Store.Save(sess); err != nil {
		return err
	}

	// Block until cancel / deadline.
	<-ctx.Done()

	// Teardown: clear session then close relay (defer also closes).
	_ = s.Store.Clear(profileID)
	_ = relay.Close()

	err := ctx.Err()
	if err == context.Canceled || err == context.DeadlineExceeded {
		return err
	}
	return err
}

// writeSSHConfig creates ConfigDir/ssh_config mentioning the bound LocalPort.
func writeSSHConfig(configDir, user string, port int) error {
	path := filepath.Join(configDir, "ssh_config")
	// Minimal OpenSSH-style config; HostName/IdentityFile may be placeholders.
	body := fmt.Sprintf(`# generated by remote-agent ssh --serve
Host remote-agent
  HostName 127.0.0.1
  Port %d
  User %s
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
`, port, user)
	return os.WriteFile(path, []byte(body), 0o644)
}
