package sshcmd

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// ServeService owns the local serve lifecycle: relay + session file + ssh_config.
type ServeService struct {
	Store      *FileSessionStore
	ProfileID  string
	Dial       DialFunc
	User       string
	Host       string
	ConfigDir  string
	SocketPath string
	ServePID   int
	Stdout     io.Writer
	Quiet      bool
}

// ServeReadyInfo is printed after the local relay is up and the session is saved.
type ServeReadyInfo struct {
	LocalSocket string
	User        string
	Host        string
	ConfigDir   string
	ProfileID   string
	Identity    string
	SSHConfig   string
}

// Start listens, saves an Alive session, blocks until ctx is canceled, then
// clears the session and closes the relay. Nil Dial fails before listen.
func (s *ServeService) Start(ctx context.Context) error {
	if s == nil {
		return errors.New("ServeService is nil")
	}
	if s.Dial == nil {
		return errors.New("dial not configured: Dial is required")
	}
	if s.Store == nil {
		return errors.New("session store not configured")
	}
	profileID := s.ProfileID
	if profileID == "" {
		profileID = "default"
	}
	user := s.User
	if user == "" {
		user = "agent"
	}
	host := s.Host
	if host == "" {
		host = "remote-agent"
	}
	if s.ConfigDir == "" {
		return errors.New("configDir is required")
	}
	if err := os.MkdirAll(s.ConfigDir, 0o700); err != nil {
		return err
	}
	if err := os.Chmod(s.ConfigDir, 0o700); err != nil {
		return err
	}
	socketPath := s.SocketPath
	if socketPath == "" {
		socketPath = filepath.Join(s.ConfigDir, "relay.sock")
	}

	relay := &LocalRelay{Dial: s.Dial, Network: "unix", Address: socketPath}
	if err := relay.Start(); err != nil {
		return err
	}
	defer func() { _ = relay.Close() }()
	if relay.LocalAddress() == "" {
		return errors.New("relay did not bind a local socket")
	}
	if err := writeSSHConfig(s.ConfigDir, host, user, socketPath); err != nil {
		return err
	}

	sess := &Session{
		LocalSocket: socketPath,
		User:        user,
		Host:        host,
		ConfigDir:   s.ConfigDir,
		ServePID:    s.ServePID,
		ProfileID:   profileID,
		Alive:       true,
	}
	if err := s.Store.Save(sess); err != nil {
		return err
	}
	if !s.Quiet {
		printServeReady(s.Stdout, ServeReadyInfo{
			LocalSocket: socketPath,
			User:        user,
			Host:        host,
			ConfigDir:   s.ConfigDir,
			ProfileID:   profileID,
			Identity:    filepath.Join(s.ConfigDir, "id_ed25519"),
			SSHConfig:   filepath.Join(s.ConfigDir, "ssh_config"),
		})
	}

	<-ctx.Done()
	_ = s.Store.Clear(profileID)
	_ = relay.Close()
	if err := ctx.Err(); err == context.Canceled || err == context.DeadlineExceeded {
		if !s.Quiet {
			printServeStopped(s.Stdout)
		}
		return nil
	} else {
		return err
	}
}

// FormatServeReady returns the ready banner (always ends with \n).
func FormatServeReady(info ServeReadyInfo) string {
	id := info.Identity
	if id == "" && info.ConfigDir != "" {
		id = filepath.Join(info.ConfigDir, "id_ed25519")
	}
	cfg := info.SSHConfig
	if cfg == "" && info.ConfigDir != "" {
		cfg = filepath.Join(info.ConfigDir, "ssh_config")
	}
	host := info.Host
	if host == "" {
		host = "remote-agent"
	}
	user := info.User
	if user == "" {
		user = "agent"
	}
	return fmt.Sprintf(`SSH serve ready
  Socket:    %s
  Host:      %s
  User:      %s
  Identity:  %s
  Config:    %s

In another terminal:
  remote-agent ssh
  ssh %s@%s

Tunnel up; Ctrl-C to stop.
`, info.LocalSocket, host, user, id, cfg, user, host)
}

func printServeReady(w io.Writer, info ServeReadyInfo) {
	if w != nil {
		_, _ = io.WriteString(w, FormatServeReady(info))
	}
}

func printServeStopped(w io.Writer) {
	if w != nil {
		_, _ = io.WriteString(w, "SSH serve stopped.\n")
	}
}

// writeSSHConfig creates ConfigDir/ssh_config for the stable local Unix socket.
func writeSSHConfig(configDir, host, user, socketPath string) error {
	path := filepath.Join(configDir, "ssh_config")
	identity := filepath.Join(configDir, "id_ed25519")
	body := fmt.Sprintf(`# generated by remote-agent ssh --serve
Host %s
  HostName 127.0.0.1
  User %s
  IdentityFile %s
  IdentitiesOnly yes
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  LogLevel ERROR
  ProxyCommand /usr/bin/nc -U %s
`, host, user, shellQuote(identity), shellQuote(socketPath))
	return os.WriteFile(path, []byte(body), 0o600)
}

func shellQuote(s string) string {
	if !strings.ContainsAny(s, " \t\n'\\\"") {
		return s
	}
	return "'" + strings.ReplaceAll(s, "'", "'\\''") + "'"
}
